In [1]:
import pandas as pd
import numpy as np

In [2]:
valeurs = [40000, 60000, 80000, 90000, 100000, 120000, 124187]

In [3]:
filename = 'recapitulatif-m-6-1-20000.csv'

In [4]:
data = pd.read_csv(filename)

In [5]:
prec_val = 20001
for val in valeurs:
    tmp_filename = f'recapitulatif-m-6-{prec_val}-{val}.csv'
    prec_val = val + 1
    tmp_data = pd.read_csv(tmp_filename)
    data = pd.concat([data, tmp_data], join='inner')

In [6]:
data

,Unnamed: 0,Base,Compo2,Compo3,UNXP,DynEvo,NB_TO_EXPLAIN,NB_STEPS,ALL_UNXP
0,model1.csv,301,0,0,0,0,301,1,0
1,model2.csv,284,14,3,0,0,301,1,0
2,model3.csv,285,10,6,0,0,301,1,0
3,model4.csv,277,15,9,0,0,301,1,0
4,model5.csv,285,13,3,0,0,301,1,0
...,...,...,...,...,...,...,...,...,...
4182,model124183.csv,224,65,10,2,2,301,2,0
4183,model124184.csv,225,66,10,0,0,301,1,0
4184,model124185.csv,224,66,9,2,2,301,2,0
4185,model124186.csv,212,67,22,0,0,301,1,0
4186,model124187.csv,209,65,24,3,3,301,2,0

In [7]:
LesValeurs, CS = np.unique(data["ALL_UNXP"], return_counts=True)
CS = CS.cumsum()
print("les valeurs:", LesValeurs)
print("CS", CS)
PP = np.round(100.*CS/CS[-1], 3)
{LesValeurs[i]: PP[i] for i in range(len(LesValeurs))}

les valeurs: [0]
CS [124187]

{0: 100.0}

In [8]:
LesValeurs, CS = np.unique(data["NB_TO_EXPLAIN"] - data["Base"], return_counts=True)
CS = CS.cumsum()
print("les valeurs:", LesValeurs)
print("CS", CS)
PP = np.round(100.*CS/CS[-1], 3)
{LesValeurs[i]: PP[i] for i in range(len(LesValeurs))}

les valeurs: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 118 119 120 124 125 126 128]
CS [    20     41     67    107    159    201    306    417    546    710
    927   1142   1404   1666   1960   2283   2714   3177   3734   4260
   4859   5527   6283   7064   8030   9021  10061  11200  12405  13802
  15353  16913  18582  20441  22400  24456  26632  28692  30847  33156
  35554  37971  40550  43077  45720  48371  51019  53659  56363  59004
  61733  64479  67202  69766  72542  75141  77740  80347  82995  85454
  87829  90124  92392  94570  96613  98682 100587 102341 104030 105647
 107165 108638 109936 111162 112394 113485 114515 115478 116354 117161
 117915 118555 119177 119766 120241 120669 121049 121422 121752 122038
 122314 122557 122755 122920 123091 123257 123379 123478 123563 123648
 123712 123776 123826 123890 123933 123980 124011 124039 124061 124079
 124095 124110 124126 124135 124152 124162 124172 124177 124179 124180
 124181 124184 124186 124187]

{0: 0.016,
 1: 0.033,
 2: 0.054,
 3: 0.086,
 4: 0.128,
 5: 0.162,
 6: 0.246,
 7: 0.336,
 8: 0.44,
 9: 0.572,
 10: 0.746,
 11: 0.92,
 12: 1.131,
 13: 1.342,
 14: 1.578,
 15: 1.838,
 16: 2.185,
 17: 2.558,
 18: 3.007,
 19: 3.43,
 20: 3.913,
 21: 4.451,
 22: 5.059,
 23: 5.688,
 24: 6.466,
 25: 7.264,
 26: 8.101,
 27: 9.019,
 28: 9.989,
 29: 11.114,
 30: 12.363,
 31: 13.619,
 32: 14.963,
 33: 16.46,
 34: 18.037,
 35: 19.693,
 36: 21.445,
 37: 23.104,
 38: 24.839,
 39: 26.698,
 40: 28.629,
 41: 30.576,
 42: 32.652,
 43: 34.687,
 44: 36.815,
 45: 38.95,
 46: 41.082,
 47: 43.208,
 48: 45.386,
 49: 47.512,
 50: 49.71,
 51: 51.921,
 52: 54.114,
 53: 56.178,
 54: 58.414,
 55: 60.506,
 56: 62.599,
 57: 64.698,
 58: 66.831,
 59: 68.811,
 60: 70.723,
 61: 72.571,
 62: 74.397,
 63: 76.151,
 64: 77.796,
 65: 79.462,
 66: 80.996,
 67: 82.409,
 68: 83.769,
 69: 85.071,
 70: 86.293,
 71: 87.479,
 72: 88.525,
 73: 89.512,
 74: 90.504,
 75: 91.382,
 76: 92.212,
 77: 92.987,
 78: 93.693,
 79: 94.342,
 80: 94.95,
 81: 95.465,
 82: 95.966,
 83: 96.44,
 84: 96.823,
 85: 97.167,
 86: 97.473,
 87: 97.774,
 88: 98.039,
 89: 98.27,
 90: 98.492,
 91: 98.687,
 92: 98.847,
 93: 98.98,
 94: 99.117,
 95: 99.251,
 96: 99.349,
 97: 99.429,
 98: 99.498,
 99: 99.566,
 100: 99.618,
 101: 99.669,
 102: 99.709,
 103: 99.761,
 104: 99.795,
 105: 99.833,
 106: 99.858,
 107: 99.881,
 108: 99.899,
 109: 99.913,
 110: 99.926,
 111: 99.938,
 112: 99.951,
 113: 99.958,
 114: 99.972,
 115: 99.98,
 116: 99.988,
 118: 99.992,
 119: 99.994,
 120: 99.994,
 124: 99.995,
 125: 99.998,
 126: 99.999,
 128: 100.0}

In [9]:
LesValeurs, CS = np.unique(data["NB_TO_EXPLAIN"] - data["Base"] - data["Compo2"], return_counts=True)
CS = CS.cumsum()
print("les valeurs:", LesValeurs)
print("CS", CS)
PP = np.round(100.*CS/CS[-1], 3)
{LesValeurs[i]: PP[i] for i in range(len(LesValeurs))}

les valeurs: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 79 80 81 83 85]
CS [  2376   5422   9445  14493  20231  26265  32445  38603  44642  50665
  56614  62223  67648  72732  77432  81990  86160  89889  93526  96677
  99593 102269 104647 106835 108852 110573 112194 113620 114896 116010
 117073 117923 118701 119403 119990 120492 120924 121357 121699 122058
 122336 122569 122780 122968 123129 123275 123386 123485 123604 123693
 123742 123803 123851 123888 123928 123962 123995 124031 124049 124062
 124075 124089 124105 124113 124125 124135 124143 124150 124152 124153
 124158 124165 124170 124172 124177 124179 124180 124182 124183 124185
 124186 124187]

{0: 1.913,
 1: 4.366,
 2: 7.605,
 3: 11.67,
 4: 16.291,
 5: 21.15,
 6: 26.126,
 7: 31.085,
 8: 35.947,
 9: 40.797,
 10: 45.588,
 11: 50.104,
 12: 54.473,
 13: 58.567,
 14: 62.351,
 15: 66.021,
 16: 69.379,
 17: 72.382,
 18: 75.311,
 19: 77.848,
 20: 80.196,
 21: 82.351,
 22: 84.266,
 23: 86.028,
 24: 87.652,
 25: 89.037,
 26: 90.343,
 27: 91.491,
 28: 92.519,
 29: 93.416,
 30: 94.272,
 31: 94.956,
 32: 95.582,
 33: 96.148,
 34: 96.62,
 35: 97.025,
 36: 97.373,
 37: 97.721,
 38: 97.997,
 39: 98.286,
 40: 98.51,
 41: 98.697,
 42: 98.867,
 43: 99.018,
 44: 99.148,
 45: 99.266,
 46: 99.355,
 47: 99.435,
 48: 99.531,
 49: 99.602,
 50: 99.642,
 51: 99.691,
 52: 99.729,
 53: 99.759,
 54: 99.791,
 55: 99.819,
 56: 99.845,
 57: 99.874,
 58: 99.889,
 59: 99.899,
 60: 99.91,
 61: 99.921,
 62: 99.934,
 63: 99.94,
 64: 99.95,
 65: 99.958,
 66: 99.965,
 67: 99.97,
 68: 99.972,
 69: 99.973,
 70: 99.977,
 71: 99.982,
 72: 99.986,
 73: 99.988,
 74: 99.992,
 75: 99.994,
 76: 99.994,
 79: 99.996,
 80: 99.997,
 81: 99.998,
 83: 99.999,
 85: 100.0}

In [10]:
LesValeurs, CS = np.unique(data["UNXP"], return_counts=True)
CS = CS.cumsum()
print("les valeurs:", LesValeurs)
print("CS", CS)
PP = np.round(100.*CS/CS[-1], 3)
{LesValeurs[i]: PP[i] for i in range(len(LesValeurs))}

les valeurs: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 42 43 44 46 47 48 49
 50 54 56 63]
CS [ 59525  82137  94678 103230 109072 112668 115789 117715 119082 120277
 121102 121715 122254 122654 122940 123182 123343 123497 123613 123721
 123799 123871 123919 123958 123993 124014 124032 124057 124071 124087
 124102 124118 124128 124140 124145 124151 124155 124157 124160 124164
 124169 124172 124173 124175 124177 124179 124181 124183 124184 124185
 124186 124187]

{0: 47.932,
 1: 66.14,
 2: 76.238,
 3: 83.125,
 4: 87.829,
 5: 90.724,
 6: 93.238,
 7: 94.789,
 8: 95.889,
 9: 96.852,
 10: 97.516,
 11: 98.009,
 12: 98.443,
 13: 98.766,
 14: 98.996,
 15: 99.191,
 16: 99.32,
 17: 99.444,
 18: 99.538,
 19: 99.625,
 20: 99.688,
 21: 99.746,
 22: 99.784,
 23: 99.816,
 24: 99.844,
 25: 99.861,
 26: 99.875,
 27: 99.895,
 28: 99.907,
 29: 99.919,
 30: 99.932,
 31: 99.944,
 32: 99.952,
 33: 99.962,
 34: 99.966,
 35: 99.971,
 36: 99.974,
 37: 99.976,
 38: 99.978,
 39: 99.981,
 40: 99.986,
 42: 99.988,
 43: 99.989,
 44: 99.99,
 46: 99.992,
 47: 99.994,
 48: 99.995,
 49: 99.997,
 50: 99.998,
 54: 99.998,
 56: 99.999,
 63: 100.0}